apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: AccountID.dkr.ecr.ap-south-1.amazonaws.com/web-api:latest
        ports:
        - containerPort: 3000
